"""FR-17: Standardized error codes."""
from __future__ import annotations

AUTH_INVALID_SIGNATURE = "AUTH_INVALID_SIGNATURE"
RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
KNOWLEDGE_NOT_FOUND = "KNOWLEDGE_NOT_FOUND"
VALIDATION_ERROR = "VALIDATION_ERROR"
INTERNAL_ERROR = "INTERNAL_ERROR"
IP_WHITELIST_VIOLATION = "IP_WHITELIST_VIOLATION"
IP_WHITELIST_INVALID = "IP_WHITELIST_INVALID"

HTTP_STATUS_MAP = {
    AUTH_INVALID_SIGNATURE: 401,
    RATE_LIMIT_EXCEEDED: 429,
    KNOWLEDGE_NOT_FOUND: 404,
    VALIDATION_ERROR: 422,
    INTERNAL_ERROR: 500,
    IP_WHITELIST_VIOLATION: 403,
    IP_WHITELIST_INVALID: 400,
}
